### ISSUE TITLE
Text unreadable on Computer 

### ISSUE THREAD

**Issue by Arttast** [JonnyOThan/KSA-IVA-Upgrade#16]
(Tested on KSP 1.12 Windows & Linux and both using ATI Cards)
![IMG20230420181436.jpg](https://user-images.githubusercontent.com/86967683/233410408-aae66ea6-946d-4aa9-8d17-8d1848bc9906.jpg)

sorry for bad picture

**Comment by JonnyOThan** [comment]
Make sure your texture quality is set to full.  This is an issue with RPM, not KSA.
