### ISSUE TITLE
[SOLVED] Stupid question : How do I know if the mod is working?

### ISSUE THREAD

**Issue by jeancallisti** [JonnyOThan/KSA-IVA-Upgrade#7]
ckan tells me that the mod is installed.
But once in-game, what am I supposed to see?
- Is there any kind of **menu bar?**
- Are there **new pods** in the VAB (in a **separate tab?** ) or are those the **same** as the stock pods, just with a better IVA view?

I'm trying to use the VR mod and everything seems to be working except I end up with the basic IVA (non-interactive buttons and levers)

**Comment by jeancallisti** [comment]
OK, I think I got it. I think I need to switch to the correct IVA in the pod's contextual menu, with the magic button from Reviva.
When you're famliar with that stack of mods it makes sense. When you're not... What a headache to understand what mod does what! :-)
Thanks for all the hard work.

**Comment by JonnyOThan** [comment]
Glad you figured it out!  Reviva is very useful but if you’re not used to it it’s certainly confusing. The install guide does call this out, but it’s also very dense with info so not surprising it gets missed. If you have any thoughts about how to make it more obvious, I’m all ears.
